#variable
@baseUrl = http://localhost:3333

###

#get Healts
# @name healtApi
GET {{baseUrl}}/health

###
#Get Rooms
# @name getRooms
get {{baseUrl}}/rooms

###
# Create Room
# @name createRoom
POST {{baseUrl}}/rooms
Accept: application/json
Content-Type: application/json

{
  "name": "Aurelio Castro",
  "description": "You is Developer"
}

###

# @roomId = {{createRoom.response.body.$.roomId}}
@roomId = d719db66-c60a-40a5-82db-32683f9f7a69


###
#Get Question Room
# @name getQuestionsRoom
GET {{baseUrl}}/rooms/{{roomId}}/questions

###
#Create Question Room
# @name createQuestionRoom
POST {{baseUrl}}/rooms/d719db66-c60a-40a5-82db-32683f9f7a69/questions
Accept: application/application/json
Content-Type: application/json

{
  "question": "O que e react?"
}

###
#Create Question Room
# @name deleteQuestionRoom
DELETE {{baseUrl}}/rooms/{{roomId}}/questions/f4c70061-f6bc-42b0-94c4-70b950e95770

