version: '3.8'

services:
  app_servernlwagents:
    image: aureliolk/app_servernlwagents:1.0
    ports:
      - "3333:3333"
    environment:
      SERVER_URL: http://localhost
      PORT: 3333
      DATABASE_URL: postgres://aureliolk:lkb3t4kayn@nlw-agents-pg:5432/nlw_agents
      GEMINI_API_KEY: "AIzaSyAapctXWXr3dzOTmA_stNiodu5GQpQtuU4"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - nlw-agents-pg
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  
  nlw-agents-pg:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: aureliolk
      POSTGRES_PASSWORD: lkb3t4kayn
      POSTGRES_DB: nlw_agents
    volumes:
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure